name: Deploy Swagger Docs to GitHub Pages

on:
  push:
    branches:
      - main  # o cambia a 'develop' si usas esa rama

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Swagger UI files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Asegúrate de que index.html y burger-api-doc.json están en la raíz

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

